### PR TITLE
Fix record comparison.

### LINKED ISSUE #1916: Exception when comparing list of modules
```ruby
null = null();;

x = [{
  pix_fmt = null,
  codec_name = "aac",
  sample_fmt = "fltp", 
  sample_rate = "48000", 
  channel_layout = "stereo"
}, {
  pix_fmt = "yuv420p",
  codec_name = "h264",
  sample_fmt = null,
  sample_rate = null,
  channel_layout = null
  }];;

y = [{
  pix_fmt = null,
  codec_name = "aac",
  sample_fmt = "fltp", 
  sample_rate = "48000", 
  channel_layout = "stereo"
}, {
  pix_fmt = "yuv420p",
  codec_name = "h264",
  sample_fmt = null,
  sample_rate = null,
  channel_layout = null
  }];;
  
  x == y;;
Unknown position:
Error -1: Exception raised: "Assert_failure lang/lang.ml:179:11"
Raised at Lang.compare_values.aux in file "lang/lang.ml", line 179, characters 11-23
Called from Lang.compare_values.aux.cmp in file "lang/lang.ml", line 172, characters 22-46
Called from Builtins_bool.register_op.(fun) in file "lang/builtins_bool.ml", line 60, characters 18-45
Called from Evaluation.apply.f in file "lang/evaluation.ml", line 268, characters 8-12
Called from Evaluation.eval_toplevel in file "lang/evaluation.ml", line 432, characters 16-22
Called from Runtime.interactive.loop.(fun) in file "lang/runtime.ml", line 308, characters 23-72
Called from Tutils.finalize in file "tools/tutils.ml", line 100, characters 12-16
Re-raised at Tutils.finalize in file "tools/tutils.ml", line 106, characters 4-38
Called from Runtime.report in file "lang/runtime.ml", line 191, characters 12-23
```
This works when comparing the list elements only.

### PR DESCRIPTION
**Pull request by toots**
I believe that this fixes #1916 by lifting the record subcase to the common comparison function.

Also, I didn't want to have too much to think about how to define the order so I delegated to comparing the tuple `(("label", method), ...)` as a value. Please advise if that's a good idea.

Bonus: Every heard the joke about a polytechnicien, a pot on a stove with water in it, a nail on the wall, and a pack of matches? 🙂

### CODE REVIEW

**Comment by smimram** [comment]
Quick point: did you think of masking? This means that `{a = 2}.{a = "x"}` should be the same as `{a = "x"}`.

File: src/lang/lang.ml [hunk 1]
```diff
@@ -161,24 +161,48 @@ let compare_values a b =
...
-              let c = aux (h1.value, h2.value) in
+              let c = compare_values (h1, h2) in
               if c = 0 then cmp (l1, l2) else c
         in
         cmp (l1, l2)
     | Null, Null -> 0
     | Null, _ -> -1
     | _, Null -> 1
     | _ -> assert false
+  and compare_values (a, b) =
```
Comment (smimram) [inline src/lang/lang.ml:180]: This would better be moved to `Value.compare`.

Comment (smimram) [inline src/lang/lang.ml:180]:
```suggestion
  and compare_values a b =
```

**Comment by toots** [comment]
> Quick point: did you think of masking? This means that `{a = 2}.{a = "x"}` should be the same as `{a = "x"}`.

Isn't `demeth` taking care of this?

File: src/lang/lang.ml (hunk 1 above)
Comment (toots) [reply src/lang/lang.ml:180]: This is really annoying to do in the `2.0.0` branch as `Value` is nested into `Term` and the namings clash. I'll do it when backporting to `main`.

Comment (toots) [reply src/lang/lang.ml:180]: Same, I'll do it when backporting to `main`
