### PR TITLE
Fix parsing of rolling-release version.

### LINKED ISSUE #4287: `%ifversion` throws an error when using git branch name
### Description

The problem manifests itself when I build liquidsoap from a branch, say `rolling-release-v2.2.x`. In this case the version became `rolling-release-v2.3.x+git@2addd93da`.

<details>
<summary>2.3.x</summary>

```
Unknown position:

Error 9: Failure: int_of_string
Raised by primitive operation at Liquidsoap_lang__Lang_string.Version.of_string in file "src/lang/lang_string.ml", line 359, characters 55-68
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Stdlib__List.map in file "list.ml", line 92, characters 32-39
Called from Stdlib__List.map in file "list.ml", line 92, characters 32-39
Called from Liquidsoap_lang__Lang_string.Version.of_string in file "src/lang/lang_string.ml", line 359, characters 14-68
Called from Liquidsoap_lang__Term_reducer.pp_if_reducer in file "src/lang/term/term_reducer.ml", line 63, characters 8-58
Called from Liquidsoap_lang__Term_reducer.to_term in file "src/lang/term/term_reducer.ml", line 1226, characters 16-43
Called from Liquidsoap_lang__Term_reducer.to_term in file "src/lang/term/term_reducer.ml" (inlined), line 1288, characters 17-35
Called from Liquidsoap_lang__Runtime.mk_expr.(fun) in file "src/lang/runtime.ml", line 315, characters 20-52
Called from Liquidsoap_lang__Runtime.report in file "src/lang/runtime.ml", line 222, characters 8-19
```

</details>

<details>
<summary>2.2.x</summary>

```
%ifversion >= 2.0

Error 9: Failure: int_of_string
Raised by primitive operation at Liquidsoap_lang__Lang_string.Version.of_string in file "src/lang/lang_string.ml", line 352, characters 55-68
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Stdlib__List.map in file "list.ml", line 92, characters 32-39
Called from Stdlib__List.map in file "list.ml", line 92, characters 32-39
Called from Liquidsoap_lang__Lang_string.Version.of_string in file "src/lang/lang_string.ml", line 352, characters 14-68
Called from Liquidsoap_lang__Preprocessor.eval_ifdefs.token in file "src/lang/preprocessor.ml", line 60, characters 24-74
Called from Liquidsoap_lang__Preprocessor.parse_comments.token in file "src/lang/preprocessor.ml", line 454, characters 10-22
Called from Liquidsoap_lang__Preprocessor.expand_string.token in file "src/lang/preprocessor.ml", line 184, characters 12-24
Called from Liquidsoap_lang__Preprocessor.int_meth.fill in file "src/lang/preprocessor.ml", line 476, characters 10-22
Called from Liquidsoap_lang__Preprocessor.dotvar.token in file "src/lang/preprocessor.ml", line 505, characters 16-28
Called from Liquidsoap_lang__Preprocessor.uminus.token in file "src/lang/preprocessor.ml", line 518, characters 10-22
Called from Liquidsoap_lang__Preprocessor.strip_newlines.token in file "src/lang/preprocessor.ml", line 561, characters 16-28
Called from Liquidsoap_lang__Preprocessor.mk_tokenizer.(fun) in file "src/lang/preprocessor.ml", line 582, characters 28-40
Called from MenhirLib.Convert.traditional2revised.lexer in file "lib/pack/menhirLib.ml", line 152, characters 27-34
Called from Liquidsoap_lang__Parser._menhir_run_506 in file "src/lang/parser.ml", line 14658, characters 17-45
Called from Liquidsoap_lang__Runtime.from_lexbuf.(fun) in file "src/lang/runtime.ml", line 230, characters 17-62
Called from Liquidsoap_lang__Runtime.report in file "src/lang/runtime.ml", line [21](https://github.com/vitoyucepi/liquidsoap-issue-0/actions/runs/12496623899/job/34868523932#step:5:22)5, characters 12-23
```

</details>

### Steps to reproduce

<ol>

<li>
<details>
<summary>Init script</summary>

```sh
OPAM_VERSION=2.3.0;
OCAML_VERSION=4.14.2;
```
```sh
sudo apt-get update;
sudo apt-get dist-upgrade;
sudo apt-get install --no-install-recommends -y curl ca-certificates patch unzip bubblewrap git bzip2 gcc make libc6-dev g++;
sudo curl -sS -L -o /usr/local/bin/opam "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-x86_64-linux";
sudo chmod +x /usr/local/bin/opam;
opam init --bare -n;
opam switch create "$OCAML_VERSION";
eval $(opam env --switch="$OCAML_VERSION");
```

</details>
</li>

<li>
<details>
<summary>Build liquidsoap</summary>

```sh
git clone https://github.com/savonet/liquidsoap.git -b rolling-release-v2.3.x;
cd liquidsoap;
opam pin --no-action --yes .;
opam install --confirm-level=unsafe-yes liquidsoap;
```

</details>
</li>

<li>
<details>
<summary><code>main.liq</code></summary>

```ruby
%ifversion >= 2.0
print(liquidsoap.version)
%endif
```

</details>
</li>

</ol>

### Expected behavior

The version should be set from `.opam` or `dune-project` file.

### Liquidsoap version

```text
Liquidsoap rolling-release-v2.3.x+git@2addd93da
Copyright (c) 2003-2024 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.
```

### Liquidsoap build config

```text
* Liquidsoap version  : rolling-release-v2.3.x+git@2addd93da

 * Compilation options
   - Release build       : false
   - Git SHA             : 2addd93da
   - OCaml version       : 4.14.2
   - OS type             : Unix
   - Libs versions       : angstrom=0.16.1 base=v0.16.3 base.base_internalhash_types=v0.16.3 base.caml=v0.16.3 base.shadow_stdlib=v0.16.3 bigarray=[distributed with Ocaml] bigstringaf=0.10.0 bytes=[distributed with OCaml 4.02 or above] camlp-streams camomile.lib=2.0 cry=1.0.3 curl=0.9.2 domain_shims dtools=0.4.5 dune-build-info=3.17.1 dune-private-libs.dune-section=3.17.1 dune-site=3.17.1 dune-site.private=3.17.1 duppy=0.9.4 fileutils=0.6.4 gen=1.1 liquidsoap-lang=rolling-release-v2.3.x liquidsoap-lang.console=rolling-release-v2.3.x liquidsoap_builtins=rolling-release-v2.3.x-dirty liquidsoap_core=rolling-release-v2.3.x-dirty liquidsoap_optionals=rolling-release-v2.3.x-dirty liquidsoap_oss=rolling-release-v2.3.x-dirty liquidsoap_runtime=rolling-release-v2.3.x-dirty magic-mime=1.3.1 mem_usage=0.1.1 menhirLib=20240715 metadata=0.3.0 mm=0.8.6 mm.audio=0.8.6 mm.base=0.8.6 mm.image=0.8.6 mm.midi=0.8.6 mm.video=0.8.6 ppx_compare.runtime-lib=v0.16.0 ppx_hash.runtime-lib=v0.16.0 ppx_sexp_conv.runtime-lib=v0.16.0 re=1.12.0 saturn_lockfree=0.4.1 sedlex=3.3 seq=[distributed with OCaml 4.07 or above] sexplib0=v0.16.0 stdlib-shims=0.3.0 str=[distributed with Ocaml] stringext=1.6.0 threads=[distributed with Ocaml] threads.posix=[internal] unix=[distributed with Ocaml] uri=4.4.0 xml-light=2.5
   - architecture        : amd64
   - host                : x86_64-pc-linux-gnu
   - target              : x86_64-pc-linux-gnu
   - system              : linux
   - ocamlopt_cflags     : -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC
   - native_c_compiler   : gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64
   - native_c_libraries  : -lm

 * Configured paths
   - mode              : default
   - standard library  : (set by dune-site)
   - scripted binaries : (set by dune-site)
   - rundir            : (set by dune-site)
   - logdir            : (set by dune-site)
   - user cache        : $HOME/.cache/liquidsoap (override with $LIQ_CACHE_USER_DIR)
   - system cache      : (set by dune-site) (override with $LIQ_CACHE_SYSTEM_DIR)
   - camomile files    : (set by dune-site)

 * Supported input formats
   - MP3               : no (requires mad)
   - AAC               : no (requires faad)
   - Ffmpeg            : no (requires ffmpeg)
   - Flac (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Opus              : no (requires opus)
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : no (requires vorbis)
   - WAV/AIFF          : yes (native)

 * Supported output formats
   - FDK-AAC           : no (requires fdkaac)
   - FFmpeg            : no (requires ffmpeg)
   - MP3               : no (requires lame)
   - MP3 (fixed-point) : no (requires shine)
   - Flac (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Opus              : no (requires opus)
   - Speex             : no (requires speex)
   - Theora            : no (requires theora)
   - Vorbis            : no (requires vorbis)
   - WAV/AIFF          : yes (native)

 * Tags
   - AAC               : no (requires faad)
   - FFmpeg            : no (requires ffmpeg)
   - FLAC (native)     : no (requires flac)
   - Flac (ogg)        : no (requires ogg)
   - Native decoder    : yes
   - Vorbis            : no (requires vorbis)

 * Input / output
   - ALSA              : no (requires alsa)
   - AO                : no (requires ao)
   - FFmpeg            : no (requires ffmpeg)
   - JACK              : no (requires bjack)
   - NDI               : no (requires ctypes-foreign)
   - OSS               : yes
   - Portaudio         : no (requires portaudio)
   - Pulseaudio        : no (requires pulseaudio)
   - SRT               : no (requires srt)

 * Audio manipulation
   - FFmpeg            : no (requires ffmpeg)
   - LADSPA            : no (requires ladspa)
   - Lilv              : no (requires lilv)
   - Samplerate        : no (requires samplerate)
   - SoundTouch        : no (requires soundtouch)
   - StereoTool        : no (requires ctypes-foreign)

 * Video manipulation
   - camlimages        : no (requires camlimages)
   - FFmpeg            : no (requires ffmpeg)
   - frei0r            : no (requires frei0r)
   - ImageLib          : no (requires imagelib)
   - SDL               : no (requires tsdl-image & tsdl-ttf)

 * MIDI manipulation
   - DSSI              : no (requires dssi)

 * Visualization
   - GD                : no (requires gd)
   - Graphics          : no (requires graphics)
   - SDL               : no (requires tsdl-image & tsdl-ttf)

 * Additional libraries
   - FFmpeg filters    : no (requires ffmpeg)
   - FFmpeg devices    : no (requires ffmpeg)
   - inotify           : no (requires inotify)
   - irc               : no (requires irc-client-unix)
   - jemalloc          : no (requires jemalloc)
   - lo                : no (requires lo)
   - memtrace          : no (requires memtrace)
   - osc               : no (requires osc-unix)
   - ssl               : no (requires ssl)
   - sqlite3           : no (requires sqlite3)
   - tls               : no (requires tls-liquidsoap)
   - posix-time2       : no (requires posix)
   - windows service   : no (requires winsvc)
   - YAML support      : no (requires yaml)
   - XML playlists     : no (requires xmlplaylist)

 * Monitoring
   - Prometheus        : no (requires prometheus)
```

### Installation method

From source/self-built

### Additional Info

https://github.com/vitoyucepi/liquidsoap-issue-4287
https://github.com/vitoyucepi/liquidsoap-issue-4287/actions/runs/12496755303

### PR DESCRIPTION
**Pull request by smimram**
- allow "rolling-release-v" as prefix to the version
- consider "x" in the version number as -1

Fixes #4287.

### CODE REVIEW

File: src/lang/lang_string.ml [hunk 1]
```diff
@@ -352,11 +352,14 @@ module Version = struct
...
   (* We assume something like, 2.0.0+git@7e211ffd *)
   let of_string s : t =
-    let rex = Re.Pcre.regexp "([\\.\\d]+)([^\\.]+)?" in
+    let rex = Re.Pcre.regexp "(?:rolling-release-v)?([\\.\\dx]+)([^\\.]+)?" in
     let sub = Re.Pcre.exec ~rex s in
     let num = Re.Pcre.get_substring sub 1 in
     let str = try Re.Pcre.get_substring sub 2 with _ -> "" in
-    let num = String.split_on_char '.' num |> List.map int_of_string in
+    let num =
+      let int_of_string s = if s = "x" then -1 else int_of_string s in
```
Comment (toots) [inline src/lang/lang_string.ml:360]:
```suggestion
      let int_of_string s = if s = "x" then max_int else int_of_string s in
```

**Comment by toots** [comment]
Thanks! I made `x` be `max_int`. In most situations, if we say at least version `2.3.4`, we expect `2.3.x` to be the rolling release above it (and above all released `2.3.*` versions..)
