### PR TITLE
Fix equality of records

### LINKED ISSUE #1583: Equality of records
Right now we have
```
# {x=3} == {x=5};;
- : bool = true
```
because only the unit part of records is compared...

### PR DESCRIPTION
**Pull request by smimram**
Should fix #1583.

### CODE REVIEW

File: src/lang/builtins_bool.ml [hunk 1]
```diff
@@ -27,9 +27,29 @@ let () =
...
     add_builtin name ~cat:Bool ~descr:"Comparison of comparable values."
       [("", t, None, None); ("", t, None, None)] Lang.bool_t (fun p ->
-        let a = Lang.assoc "" 1 p |> Lang.demeth in
-        let b = Lang.assoc "" 2 p |> Lang.demeth in
-        Lang.bool (op (Lang.compare_values a b)))
+        let a = Lang.assoc "" 1 p in
+        let b = Lang.assoc "" 2 p in
+        let a' = Lang.demeth a in
+        let b' = Lang.demeth b in
+        (* For records, we also compare fields. *)
```
Comment (toots) [inline src/lang/builtins_bool.ml:34]: Why only for records?

File: src/lang/builtins_bool.ml [hunk 2]
```diff
@@ -27,9 +27,29 @@ let () =
...
+        let ans =
+          if a'.Lang.value = Lang.Tuple [] && b'.Lang.value = Lang.Tuple [] then (
+            let r a =
+              let m, _ = Lang_values.V.split_meths a in
+              m
+            in
+            let a = r a in
+            let b = r b in
+            (* TODO: the order is not the expected one on records (for < we want
+               one field to be < and the other to be <=). *)
```
Comment (toots) [inline src/lang/builtins_bool.ml:44]: What do you mean?

File: src/lang/builtins_bool.ml [hunk 3]
```diff
@@ -27,9 +27,29 @@ let () =
...
+            List.for_all
+              (fun (l, v) ->
+                let v' = List.assoc l b in
+                op (Lang.compare_values v v'))
+              a )
```
Comment (toots) [inline src/lang/builtins_bool.ml:49]: Do you need to also test the other direction, i.e. that all methods from `b` are in `a`?

File: src/lang/lang_types.ml [hunk 4]
```diff
@@ -666,12 +667,20 @@ let rec bind a0 b =
...
                   let rec check b =
-                    let b = demeth b in
+                    let m, b = split_meths b in
                     match b.descr with
                       | Ground _ -> ()
                       | EVar (j, c) ->
                           if List.mem Ord c then ()
                           else b.descr <- EVar (j, Ord :: c)
+                      | Tuple [] ->
+                          (* For records, we want to ensure that all fields are ordered. *)
```
Comment (toots) [inline src/lang/lang_types.ml:677]: What does that entail?

File: tests/language/record.liq [hunk 5]
```diff
@@ -70,7 +70,11 @@ def f() =
   ignore(list.hd(l).x)
   l = [b,a]
   ignore(list.hd(l).x)
-  def f(c) = [a,c] end      
+  def f(c) = [a,c] end
+
+  # Equality
+  t({a = 5} == {a = 5}, true)
+  t({a = 5} == {a = 6}, false)
```
Comment (toots) [inline tests/language/record.liq:77]:
```suggestion
  t({a = 5} == {a = 6}, false)
  t({a = 5, b = 3} == {a = 6}, false)
  t({a = 5} == {a = 6, b = 4}, false)
```

**Review by toots — COMMENTED** [review]
Some questions!

File: tests/language/record.liq (hunk 5 above)
Comment (toots) [reply tests/language/record.liq:77]: Any maybe some more, like positive tests etc.?

File: src/lang/builtins_bool.ml (hunk 1 above)
Comment (smimram) [reply src/lang/builtins_bool.ml:34]: My idea is that we would tend to write something like
```
if http.get("http://...") == "bla" then
  ...
end
```
to compare the result of getting a page. And we don't wan't to take methods in accounts in this case.

And most of the time, excepting for records, fields are functions, which we cannot compare...

File: src/lang/builtins_bool.ml (hunk 2 above)
Comment (smimram) [reply src/lang/builtins_bool.ml:44]: Given records `r` and `s` with two fields `a` and `b`, the current implementations declares that `r < s` when both `r.a < s.a` and `r.b < s.b` whereas the natural order is rather
- `r.a < r.a` and `r.b <= s.b`, or
- `r.a <= r.a` and `r.b < s.b`

This could be fixed but I doubt that it's worth cluttering the code because I don't think that `<` comparison will be used that much on records...

File: src/lang/builtins_bool.ml (hunk 3 above)
Comment (smimram) [reply src/lang/builtins_bool.ml:49]: We compare two things of the same type, so `a` and `b` should have the same methods.

File: src/lang/lang_types.ml (hunk 4 above)
Comment (smimram) [reply src/lang/lang_types.ml:677]: For a record to be orderable, all its fields have to be orderable. For other values, as explained above, we don't compare the fields, so we don't check for orderability (and again, they are functions in general, so they would not be orderable).

File: tests/language/record.liq (hunk 5 above)
Comment (smimram) [reply tests/language/record.liq:77]: Argh, I thought that
```
{a = 5, b = 3} == {a = 6}
```
would not type because the two don't have the same type, but I was apparently wrong...

File: src/lang/builtins_bool.ml (hunk 2 above)
Comment (toots) [reply src/lang/builtins_bool.ml:44]: Works for me.

File: src/lang/builtins_bool.ml (hunk 3 above)
Comment (toots) [reply src/lang/builtins_bool.ml:49]: Ohh okay yes.

File: tests/language/record.liq (hunk 5 above)
Comment (toots) [reply tests/language/record.liq:77]: That might have consequence on your assumption above?
